#!/usr/bin/env python3
"""arg_text_audit.py - extract EVERY user-visible string from the DC34 ARG source
into one styled HTML report, so the whole game's copy can be proofread without
slogging through it over serial.

It pulls: the P3 room/item tables (structured), and every string literal that is
an argument to a Serial.print*/F() call across the ARG modules, grouped by the
function it lives in (the "scene"). Run:  py -3 scripts/arg_text_audit.py
Output: docs/arg-text-audit.html  (open in a browser).
"""
import os, re, html

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
FILES = [
    ("arg_clipcli.h",   "clipcli - dispatcher, help, status, hints, reset"),
    ("arg_p2_hack.h",   "P2 - The Hack (ROBCO terminal)"),
    ("arg_p3_dork.h",   "P3 - Dork (Zork-like text adventure)"),
    ("arg_p4_captcha.h","P4 - Captcha (the infinite troll)"),
    ("arg_p5_call.h",   "P5 - The Call (finale + reward keypad)"),
]

STR_RE  = re.compile(r'"((?:[^"\\]|\\.)*)"')
FUNC_RE = re.compile(r'^\s*static\s+[\w:<>]+[\s\*&]+(\w+)\s*\(')
# strings that are pure formatting/keys, not prose worth proofreading
SKIP_RE = re.compile(r'^[\s>%sdulu\\rn0-9.\-]*$')

def clean(s):
    s = s.replace('\\r\\n', ' / ').replace('\\n', ' / ').replace('\\t', ' ')
    s = s.replace('\\"', '"').replace('\\\\', '\\')
    return re.sub(r'\s+', ' ', s).strip()

def parse_table(text, decl):
    """Grab string literals from each row of a `... decl[...] = { ... };` block."""
    m = re.search(re.escape(decl) + r'.*?=\s*\{(.*?)\n\};', text, re.S)
    if not m:
        return []
    rows = []
    for line in m.group(1).splitlines():
        line = line.strip()
        if not line.startswith('{'):
            continue
        rows.append([clean(x) for x in STR_RE.findall(line)])
    return rows

def extract(path):
    text = open(path, encoding='utf-8', errors='replace').read()
    rooms = parse_table(text, 'P3R')
    items = parse_table(text, 'P3I')
    scenes, cur, seen = [], None, set()
    for raw in text.splitlines():
        fm = FUNC_RE.match(raw)
        if fm:
            cur = fm.group(1)
            continue
        if 'Serial.' not in raw and not re.search(r'\bF\s*\(', raw):
            continue
        for lit in STR_RE.findall(raw):
            c = clean(lit)
            if not c or SKIP_RE.match(lit):
                continue
            key = (cur, c)
            if key in seen:
                continue
            seen.add(key)
            if not scenes or scenes[-1][0] != cur:
                scenes.append((cur, []))
            scenes[-1][1].append(c)
    return rooms, items, scenes

CSS = """body{font:15px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;max-width:960px;margin:2rem auto;padding:0 1rem;color:#1b1b1b}
h1{border-bottom:3px solid #2a6}h2{margin-top:2.5rem;border-bottom:1px solid #ccc;color:#185}
h3{margin:1.4rem 0 .3rem;color:#444;font-family:monospace}
table{border-collapse:collapse;width:100%;margin:.5rem 0}td,th{border:1px solid #ddd;padding:.4rem .6rem;vertical-align:top;text-align:left}
th{background:#f0f7f3}td.k{font-family:monospace;white-space:nowrap;color:#185;font-weight:600}
ul{margin:.2rem 0 1rem}li{margin:.15rem 0}.meta{color:#777;font-size:13px}
.fmt{color:#a50;font-family:monospace}code{background:#f4f4f4;padding:0 .2rem}"""

def esc(s):
    s = html.escape(s)
    return re.sub(r'(%[0-9]*[sdulx]|%04u|%lu)', r'<span class="fmt">\1</span>', s)

def main():
    out = ['<!doctype html><meta charset="utf-8"><title>Clip-Boy ARG - text audit</title>',
           f'<style>{CSS}</style>',
           '<h1>Clip-Boy ARG - full text audit</h1>',
           '<p class="meta">Every user-visible string in the ARG source, extracted for proofreading. '
           'Generated by <code>scripts/arg_text_audit.py</code> - regenerate after editing copy. '
           '<span class="fmt">%s</span>-style spans are runtime-filled values.</p>']
    for fn, title in FILES:
        path = os.path.join(REPO, fn)
        if not os.path.exists(path):
            continue
        rooms, items, scenes = extract(path)
        out.append(f'<h2>{esc(title)} <span class="meta">({fn})</span></h2>')
        if rooms:
            out.append('<h3>Rooms</h3><table><tr><th>#</th><th>Name</th><th>Description</th></tr>')
            for i, r in enumerate(rooms):
                nm = r[0] if r else ''
                ds = r[1] if len(r) > 1 else ''
                out.append(f'<tr><td>{i}</td><td class="k">{esc(nm)}</td><td>{esc(ds)}</td></tr>')
            out.append('</table>')
        if items:
            out.append('<h3>Items</h3><table><tr><th>kw</th><th>Name</th><th>Examine text</th></tr>')
            for it in items:
                kw = it[0] if it else ''
                nm = it[1] if len(it) > 1 else ''
                ex = it[2] if len(it) > 2 else ''
                out.append(f'<tr><td class="k">{esc(kw)}</td><td class="k">{esc(nm)}</td><td>{esc(ex)}</td></tr>')
            out.append('</table>')
        for func, strs in scenes:
            if not strs:
                continue
            out.append(f'<h3>{esc(func or "(file scope)")}()</h3><ul>')
            for s in strs:
                out.append(f'<li>{esc(s)}</li>')
            out.append('</ul>')
    dst = os.path.join(REPO, 'docs', 'arg-text-audit.html')
    open(dst, 'w', encoding='utf-8').write('\n'.join(out))
    print('wrote', dst)

if __name__ == '__main__':
    main()
