#!/usr/bin/env python3
"""Convert an audio file to the Clip-Boy radio PCM format (mono, 8-bit G.711 mu-law, 11025 Hz).

Radio audio target (design doc DC34-129 sec 3): MONO, 8-bit G.711 mu-law, 11025 Hz
-> ~11 KB/s -> ~10.6 min in the ~7 MB littlefs budget. mu-law gives ~12-bit
perceptual dynamic range at 1 byte/sample -- best quality at that budget AND the
on-brand AM-radio grit. The device expands mu-law -> int16 via a 256-entry table
and STREAMS in chunks (never decode-whole -- minutes of int16 would blow PSRAM).

Two output modes:
  * C array (Phase-1 spike: decode-whole short clips, gated behind RADIO_PCM_TEST):
        py -3 scripts/audio_to_pcm.py <input> <output.c> <symbol> [rate]
  * Raw littlefs file (Phase-2 streamed beds -> pack into the littlefs data/ dir):
        py -3 scripts/audio_to_pcm.py --raw <input> <output.ulaw> [rate]
    The .ulaw file is headerless mono 8-bit mu-law at <rate>. Drop it in the
    littlefs `data/` dir; the device's player reads the rate from the manifest.

Both modes print the clip's share of the ~7 MB audio budget so you can plan ~10 min.
Requires ffmpeg on PATH.
"""
import os
import subprocess
import sys

RATE_DEFAULT = 11025
LFS_AUDIO_BUDGET = 7.0 * 1024 * 1024   # ~7 MB usable in the littlefs partition


def encode_mulaw(src, rate):
    # ffmpeg: decode -> mono -> target rate -> raw G.711 mu-law bytes on stdout.
    cmd = ["ffmpeg", "-v", "error", "-i", src,
           "-ac", "1", "-ar", str(rate), "-f", "mulaw", "-"]
    try:
        return subprocess.run(cmd, check=True, stdout=subprocess.PIPE).stdout
    except FileNotFoundError:
        sys.exit("ERROR: ffmpeg not found on PATH")
    except subprocess.CalledProcessError as e:
        sys.exit(f"ERROR: ffmpeg failed ({e.returncode})")


def main():
    args = sys.argv[1:]
    raw_mode = bool(args) and args[0] == "--raw"
    if raw_mode:
        args = args[1:]
    if (raw_mode and len(args) < 2) or (not raw_mode and len(args) < 3):
        print(__doc__)
        sys.exit(2)

    src, out = args[0], args[1]
    rate = int(args[2 if raw_mode else 3]) if len(args) > (2 if raw_mode else 3) else RATE_DEFAULT
    data = encode_mulaw(src, rate)
    n = len(data)
    secs = n / rate if rate else 0
    pct = 100.0 * n / LFS_AUDIO_BUDGET

    if raw_mode:
        with open(out, "wb") as f:
            f.write(data)
        print(f"Wrote {out}: {n} bytes mu-law @ {rate} Hz (~{secs:.1f}s) "
              f"-- {pct:.1f}% of the ~7MB littlefs audio budget")
    else:
        sym = args[2]
        lines = [
            "// Generated by scripts/audio_to_pcm.py -- DO NOT EDIT. Regenerate to update.",
            f"// source: {os.path.basename(src)}  mono 8-bit mu-law @ {rate} Hz  "
            f"{n} samples (~{secs:.1f}s, {n/1024:.0f} KB, {pct:.1f}% of audio budget)",
            "#ifdef RADIO_PCM_TEST",
            "#include <stdint.h>",
            "// ESP32 maps flash into the address space, so a file-scope const array",
            "// lands in flash rodata and is directly readable -- no PROGMEM needed.",
            f"const uint32_t {sym}_rate = {rate};",
            f"const uint32_t {sym}_len  = {n};",
            f"const uint8_t {sym}_ulaw[] = {{",
        ]
        for i in range(0, n, 20):
            lines.append("  " + ",".join(str(b) for b in data[i:i + 20]) + ",")
        lines += ["};", "#endif // RADIO_PCM_TEST", ""]
        with open(out, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(lines))
        print(f"Wrote {out}: {n} samples (~{secs:.1f}s), {n/1024:.0f} KB mu-law @ {rate} Hz")


if __name__ == "__main__":
    main()
