#!/usr/bin/env python3
"""bin2c.py — embed a binary file as a C byte array (+ a header with extern + len).

Usage: py -3 scripts/bin2c.py <input> <out_basename> <symbol>
Emits <out_basename>.c (the array, C linkage) and <out_basename>.h (extern decl +
<SYMBOL>_LEN #define). Used to bake a radio MP3 into flash so it streams with no
SD/littlefs dependency (MVP). Big clips belong in littlefs/SD, not here.
"""
import sys, os

def main():
    if len(sys.argv) != 4:
        print("usage: bin2c.py <input> <out_basename> <symbol>", file=sys.stderr)
        return 2
    inp, base, sym = sys.argv[1], sys.argv[2], sys.argv[3]
    data = open(inp, "rb").read()
    n = len(data)
    macro = sym.upper() + "_LEN"
    with open(base + ".c", "w", newline="\n") as f:
        f.write("// Generated by scripts/bin2c.py from %s (%d bytes). Do not edit.\n"
                % (os.path.basename(inp), n))
        f.write("#include <stdint.h>\n")
        f.write("const uint8_t %s[] = {\n" % sym)
        for i in range(0, n, 16):
            row = ",".join("0x%02x" % b for b in data[i:i+16])
            f.write("  " + row + ",\n")
        f.write("};\n")
        f.write("const uint32_t %s_len = %du;\n" % (sym, n))
    with open(base + ".h", "w", newline="\n") as f:
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write("// Generated by scripts/bin2c.py from %s. Do not edit.\n" % os.path.basename(inp))
        f.write("#define %s %du\n" % (macro, n))
        f.write("#ifdef __cplusplus\nextern \"C\" {\n#endif\n")
        f.write("extern const uint8_t %s[];\n" % sym)
        f.write("extern const uint32_t %s_len;\n" % sym)
        f.write("#ifdef __cplusplus\n}\n#endif\n")
    print("wrote %s.c + %s.h (%d bytes, %s)" % (base, base, n, macro))
    return 0

if __name__ == "__main__":
    sys.exit(main())
