#!/usr/bin/env python3
"""
build_rift_placeholder.py -- generate rift_boot_placeholder.c, the committed
default art for the --rift (BADGE_QUANTUM_RIFT) boot screen.

It's a plain 320x240 "CUSTOM BOOT SCREEN" image so the moddable-boot capability
ships publicly without any private art. The file is guarded so it only compiles
when NO user art is present (no rift_art_present.h). Modders replace it by
dropping PNGs in images/rift/ and running scripts/build_rift_screens.py.

Run once (output is committed):  py -3 scripts/build_rift_placeholder.py
"""
import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
W, H = 320, 240

im = Image.new("RGB", (W, H), (0, 0, 0))
d = ImageDraw.Draw(im)
big = ImageFont.truetype(r"C:\Windows\Fonts\seguisb.ttf", 30)
small = ImageFont.truetype(r"C:\Windows\Fonts\segoeui.ttf", 14)
d.text((W // 2, 104), "CUSTOM BOOT SCREEN", font=big, fill=(255, 255, 255), anchor="mm")
d.text((W // 2, 146),
       "Replace me: drop a 320x240 PNG in\nimages/rift/ and run build_rift_screens.py",
       font=small, fill=(110, 110, 110), anchor="ma", align="center")

data = bytearray()
for (r, g, b) in im.getdata():
    v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    data += bytes((v & 0xFF, (v >> 8) & 0xFF))

lines = [
    "// Auto-generated by scripts/build_rift_placeholder.py -- committed default",
    "// art for the --rift boot screen. Generic 320x240 'CUSTOM BOOT SCREEN'.",
    "//",
    "// Compiles ONLY when no user art is present (see rift_art_present.h). Add",
    "// your own: images/rift/*.png + scripts/build_rift_screens.py. Both images",
    "// (img_rift_loading + img_rift_clippy) share this one placeholder bitmap.",
    "#if defined(BADGE_QUANTUM_RIFT) && (!defined(__has_include) || !__has_include(\"rift_art_present.h\"))",
    '#include <pgmspace.h>',
    '#include "lvgl.h"',
    "",
    "static const uint8_t img_rift_placeholder_map[] PROGMEM = {",
]
for i in range(0, len(data), 16):
    lines.append("    " + ",".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
lines += ["};", ""]
for sym in ("img_rift_loading", "img_rift_clippy"):
    lines += [
        f"const lv_image_dsc_t {sym} = {{",
        "    .header = {",
        "        .magic = LV_IMAGE_HEADER_MAGIC,",
        "        .cf = LV_COLOR_FORMAT_RGB565,",
        "        .flags = 0,",
        f"        .w = {W},",
        f"        .h = {H},",
        f"        .stride = {W * 2},",
        "    },",
        "    .data_size = sizeof(img_rift_placeholder_map),",
        "    .data = img_rift_placeholder_map,",
        "};",
        "",
    ]
lines += ['#endif  // placeholder active only without user art', ""]

out = os.path.join(ROOT, "rift_boot_placeholder.c")
open(out, "w", encoding="utf-8").write("\n".join(lines))
print(f"wrote rift_boot_placeholder.c ({W}x{H} RGB565 placeholder, {len(data)} bytes)")
