"""Build the Flying-Clippy screensaver sprite set (LVGL 9 A8, theme-recolored).

Source: the two wing frames in OneDrive. For each frame we crop to the alpha
bounding box, bank by 5.25 deg (nose-up toward the up-left flight path), emit 3
parallax sizes, and convert to A8 (alpha-only): the sprite is composited over
black, so brightness -> alpha (transparent bg -> 0). The saver recolors each
sprite to the active UI palette via image_recolor (like the mascot), so the
swarm matches the theme. A8 is 1 byte/px (vs 3 for RGB565A8) and blends cheap.

Output: flying_clippy_imgs.c (repo root) with 6 lv_image_dsc_t:
  clippy_{up,down}_{l,m,s}

Run:  py -3 scripts/build_flying_clippy.py
Requires: Pillow
"""
import os
from PIL import Image

SRC = r"C:\Users\data\OneDrive\esp\documents\Images\Flying Clippies"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "flying_clippy_imgs.c")
ANGLE   = -5.25                       # CW: front (left) tips up to climb up-left
HEIGHTS = [60, 44, 30]                # large(near) / med / small(far)
TAGS    = ["l", "m", "s"]
FRAMES  = [("FlyingClippy_Up.png", "up"), ("FlyingClippy_Down.png", "down")]

def to_a8(img):
    """Composite over black -> brightness becomes alpha (transparent -> 0)."""
    img = img.convert("RGBA")
    bg = Image.new("RGBA", img.size, (0, 0, 0, 255))
    l = Image.alpha_composite(bg, img).convert("L")
    w, h = l.size
    return w, h, l.tobytes()

def emit(f, name, w, h, data):
    f.write(f'static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST '
            f'uint8_t {name}_map[] = {{\n')
    for i, bb in enumerate(data):
        if i % 16 == 0:
            f.write('    ')
        f.write(f'0x{bb:02x},')
        if i % 16 == 15 or i == len(data) - 1:
            f.write('\n')
    f.write('};\n')
    f.write(f'const lv_image_dsc_t {name} = {{\n')
    f.write('  .header = { .magic = LV_IMAGE_HEADER_MAGIC, '
            '.cf = LV_COLOR_FORMAT_A8, .flags = 0,\n')
    f.write(f'    .w = {w}, .h = {h}, .stride = {w}, .reserved_2 = 0 }},\n')
    f.write(f'  .data_size = sizeof({name}_map), .data = {name}_map, .reserved = NULL,\n')
    f.write('};\n\n')

def main():
    total = 0
    with open(OUT, "w") as f:
        f.write('// Auto-generated by scripts/build_flying_clippy.py -- do not hand-edit.\n')
        f.write('// A8 alpha sprites; the saver recolors them to the active UI palette.\n')
        f.write('#include <lvgl.h>\n\n')
        for fname, ftag in FRAMES:
            src = Image.open(os.path.join(SRC, fname)).convert("RGBA")
            bbox = src.getbbox()
            if bbox:
                src = src.crop(bbox)
            rot = src.rotate(ANGLE, expand=True, resample=Image.BICUBIC)
            for ht, st in zip(HEIGHTS, TAGS):
                ww = max(1, round(rot.width * ht / rot.height))
                im = rot.resize((ww, ht), Image.LANCZOS)
                w, h, data = to_a8(im)
                emit(f, f"clippy_{ftag}_{st}", w, h, data)
                total += len(data)
                print(f"  clippy_{ftag}_{st}: {w}x{h}  {len(data)} B")
    print(f"OK -> {OUT}  ({total} B total)")

if __name__ == "__main__":
    main()
