#!/usr/bin/env python3
"""gen_postcon_site.py -- build the POST-CON companion web page for Clip-Boy.

A single self-contained (inline CSS+JS, no external JS/CSS/fonts) static page,
hostable on GitHub Pages, that players use AFTER DEFCON 34 to:
  (a) browse every collectible/tag with its HR bump-pattern so they can print
      ones they missed,
  (b) track which they've collected (localStorage), and
  (c) finish ARG puzzle 5 (P5) offline, without the phone IVR.

SINGLE SOURCE OF TRUTH: the collectible catalog is read from data/collectibles.csv;
the HR bump-pattern is computed CLIENT-SIDE by a JS port of the firmware's
SECDED(12,7) anchor encoder (scripts/hr_spec/secded.py + pattern_hardness.py,
same math as scripts/id_to_code.py). The P5 code computer mirrors arg_unlock.h's
crypto core: HMAC-SHA256(secret32, "%04u"(nonce)) -> first 4 bytes BE uint32
-> % 100000000 -> "%08u" -- computed in-browser with WebCrypto SubtleCrypto.

⚠ SECURITY: this page ships with a TEST secret (32 bytes of 0x11). The REAL ARG
secret is NEVER read or embedded here. See the PUBLISH CHECKLIST in the page
footer / the task report.

Only collectible IMAGES are fetched cross-origin (from the public Netlify site
https://clipboy.netlify.app/coll/<id>); everything else is inline.

Usage:
  py -3 scripts/gen_postcon_site.py [OUT_HTML]
    OUT_HTML defaults to postcon/index.html inside this (private) repo.
"""
import csv
import os
import sys
import json
import html
import subprocess
import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CSV_PATH = os.path.join(ROOT, "data", "collectibles.csv")
DEFAULT_OUT = os.path.join(ROOT, "postcon", "index.html")

# Public Netlify image host. Verified from scripts/build_web_images.py (writes a
# _redirects mapping "/coll/:id -> /img/:id.png") + scripts/build_qr_codes.py
# (default --base clipboy.netlify.app, the URL baked into the printed HR-tag QRs).
IMG_BASE = "https://clipboy.netlify.app/coll"

# TEST secret only. 32 bytes of 0x11.
# POST-CON PUBLISH: replace TEST_SECRET_HEX with the real ARG_HMAC_SECRET_HEX
# (from 1Password) at publish time. NEVER commit the real secret.
TEST_SECRET_HEX = "1111111111111111111111111111111111111111111111111111111111111111"


def git(*args, default=""):
    try:
        return subprocess.check_output(["git", "-C", ROOT, *args],
                                       stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return default


def esc(s):
    return html.escape(s or "", quote=True)


def load_catalog():
    """Read collectibles.csv -> ordered list of dicts (by ID)."""
    rows = []
    with open(CSV_PATH, newline="", encoding="utf-8", errors="replace") as f:
        r = csv.DictReader(f)
        for row in r:
            ids = (row.get("ID") or "").strip()
            if not ids.isdigit():
                continue
            rows.append({
                "id": int(ids),
                "title": (row.get("Title") or "").strip(),
                "source": (row.get("Source") or "").strip(),
                "tier": (row.get("Tier") or "").strip(),
                "desc": (row.get("Description") or "").strip(),
            })
    rows.sort(key=lambda x: x["id"])
    return rows


def render(catalog):
    commit = git("rev-parse", "--short", "HEAD", default="unknown")
    # Commit date, not wall-clock now() -> the page is a byte-reproducible function of
    # (data/collectibles.csv, the HR encoder, HEAD), so the build-chain staleness check
    # is a clean diff (any change is real, never a timestamp).
    built = git("show", "-s", "--format=%cs", "HEAD", default="unknown")
    data_json = json.dumps(catalog, ensure_ascii=False, separators=(",", ":"))
    n = len(catalog)

    return f"""<!--
  ============================================================================
  DO NOT PUBLISH BEFORE DEFCON 34 ENDS.
  This page reveals ALL collectible HR-code bump patterns AND the P5 ARG
  unlock-code computer. Publishing it before the con is over hands out every
  answer. This build ships with a TEST secret (32x 0x11); the real ARG secret
  is injected only at post-con publish time (see PUBLISH CHECKLIST in footer).
  Generated by scripts/gen_postcon_site.py from data/collectibles.csv.
  ============================================================================
-->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="color-scheme" content="dark light">
<meta name="robots" content="noindex, nofollow">
<title>Clip-Boy &middot; Post-Con Companion</title>
<style>
  :root {{
    --bg:#0b0d0a; --panel:#12160f; --panel2:#171c12; --line:#2c3a22;
    --amber:#ffb642; --amber-dim:#c98f34; --green:#7ee081; --red:#ff6a5a;
    --text:#e8dcc0; --muted:#9a9070; --tagbg:#3a2a12; --tagfg:#ffcf7a; --hh:150px;
    --cell-on:#ffb642; --cell-off:#1c2416;
  }}
  * {{ box-sizing:border-box; }}
  html {{ -webkit-text-size-adjust:100%; scroll-behavior:smooth; }}
  body {{
    margin:0; background:var(--bg); color:var(--text);
    font:16px/1.55 ui-monospace,"Cascadia Mono",Consolas,"DejaVu Sans Mono",monospace;
    padding-bottom:env(safe-area-inset-bottom);
  }}
  a {{ color:var(--amber); }}
  .warnbar {{
    background:repeating-linear-gradient(45deg,#3a1010,#3a1010 12px,#2a0c0c 12px,#2a0c0c 24px);
    color:#ffd9d2; border-bottom:2px solid #7a2018; padding:10px 14px;
    font-size:13px; text-align:center; letter-spacing:.4px;
  }}
  .warnbar b {{ color:#ff9a8c; }}
  .warnbar button {{
    margin-left:10px; background:#2a0c0c; color:#ffd9d2; border:1px solid #7a2018;
    border-radius:6px; padding:3px 9px; font:inherit; font-size:12px; cursor:pointer;
  }}
  header {{
    position:sticky; top:0; z-index:5; background:linear-gradient(#0b0d0aee,#0b0d0acc);
    backdrop-filter:blur(4px); border-bottom:1px solid var(--line);
    padding:12px 16px 10px; padding-top:calc(10px + env(safe-area-inset-top));
  }}
  h1 {{ margin:0; font-size:20px; letter-spacing:1px; color:var(--amber);
        text-shadow:0 0 8px #ffb64233; }}
  .sub {{ margin:2px 0 10px; color:var(--muted); font-size:12.5px; }}
  .controls {{ display:flex; flex-wrap:wrap; gap:8px; align-items:center; }}
  #q {{
    flex:1 1 200px; min-width:140px; padding:11px 12px; font:inherit; color:var(--text);
    background:var(--panel); border:1px solid var(--line); border-radius:8px;
  }}
  #q::placeholder {{ color:var(--muted); }}
  #q:focus {{ outline:none; border-color:var(--amber-dim); box-shadow:0 0 0 2px #ffb64222; }}
  .btn {{
    font:inherit; font-size:13px; color:var(--amber-dim); background:var(--panel);
    border:1px solid var(--line); border-radius:8px; padding:9px 12px; cursor:pointer;
    white-space:nowrap;
  }}
  .btn:active {{ background:var(--panel2); }}
  .btn.on {{ color:var(--bg); background:var(--amber); border-color:var(--amber); }}
  .rarity {{ display:flex; flex-wrap:wrap; gap:7px; align-items:center; margin-top:9px; }}
  .rarity .lbl {{ color:var(--muted); font-size:12px; letter-spacing:.5px; margin-right:2px; }}
  .rchip {{
    font-size:12px; color:var(--amber-dim); background:var(--panel);
    border:1px solid var(--line); border-radius:999px; padding:5px 11px; cursor:pointer;
    font-family:inherit; white-space:nowrap;
  }}
  .rchip:active {{ background:var(--panel2); }}
  .rchip.on {{ color:var(--bg); background:var(--amber); border-color:var(--amber); font-weight:600; }}
  .toc {{ display:flex; flex-wrap:wrap; gap:7px; padding:10px 16px 2px; }}
  .chip {{
    font-size:12.5px; text-decoration:none; color:var(--amber-dim);
    border:1px solid var(--line); border-radius:999px; padding:5px 11px; white-space:nowrap;
    background:none; cursor:pointer; font-family:inherit;
  }}
  .chip:active {{ background:var(--panel2); }}
  main {{ max-width:900px; margin:0 auto; padding:6px 12px 40px; }}
  .prog {{ color:var(--muted); font-size:12.5px; padding:8px 4px 2px; }}
  .prog b {{ color:var(--green); }}
  section.card {{
    background:var(--panel); border:1px solid var(--line); border-radius:10px;
    margin:12px 0; padding:14px 16px; scroll-margin-top:var(--hh);
  }}
  section.card > h2 {{
    margin:0 0 4px; font-size:16px; color:var(--amber); letter-spacing:.5px;
  }}
  section.card > p {{ margin:6px 0; color:var(--text); font-size:14px; }}
  .grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(260px,1fr)); gap:12px; }}
  .tag {{
    background:var(--panel2); border:1px solid var(--line); border-radius:10px;
    padding:12px; display:flex; gap:12px; align-items:flex-start;
  }}
  .tag.done {{ border-color:#3f6b34; box-shadow:inset 0 0 0 1px #3f6b3455; }}
  .tag .imgwrap {{
    width:88px; height:88px; flex:0 0 88px; border:1px solid var(--line); border-radius:8px;
    background:#000; display:flex; align-items:center; justify-content:center; overflow:hidden;
  }}
  .tag .imgwrap img {{ width:100%; height:100%; object-fit:contain; display:block; }}
  .tag .imgwrap .ph {{ color:var(--muted); font-size:10px; text-align:center; padding:4px; }}
  .tag .meta {{ flex:1 1 auto; min-width:0; }}
  .tag .title {{ color:var(--green); font-weight:600; font-size:14px; line-height:1.3; }}
  .tag .idline {{ color:var(--muted); font-size:12px; margin:2px 0 6px; }}
  .tier {{
    font-size:10.5px; letter-spacing:.5px; color:var(--tagfg); background:var(--tagbg);
    border:1px solid #6a4a1a; border-radius:5px; padding:1px 6px; margin-left:6px;
    vertical-align:middle; white-space:nowrap;
  }}
  /* Per-tier color coding (kept in the Pip-Boy amber-on-dark family, readable) */
  .tier.t-common    {{ color:#bcae86; background:#23281a; border-color:#454f38; }}
  .tier.t-rare      {{ color:#8fe3ff; background:#0e2630; border-color:#2b5a6b; }}
  .tier.t-legendary {{ color:#ffcf6a; background:#3a2a0e; border-color:#8a611f;
                       text-shadow:0 0 6px #ffb64244; }}
  .tier.t-0day      {{ color:#ff9ad4; background:#331025; border-color:#7a2a55; }}
  .patt {{ display:flex; gap:10px; align-items:center; margin-top:6px; }}
  .g4 {{
    display:grid; grid-template-columns:repeat(4,16px); grid-template-rows:repeat(4,16px);
    gap:3px; flex:0 0 auto;
  }}
  .g4 .c {{
    width:16px; height:16px; border-radius:3px; background:var(--cell-off);
    border:1px solid #2c3a22;
  }}
  .g4 .c.on {{ background:var(--cell-on); border-color:#ffcf7a; }}
  .g4 .c.fix {{ box-shadow:0 0 0 1px #7ee08155; border-color:#4a6b3a; }}
  .g4 .c.on.fix {{ box-shadow:0 0 0 1px #7ee08188; }}
  .ptxt {{ color:var(--muted); font-size:11px; line-height:1.35; }}
  .ptxt b {{ color:var(--amber-dim); }}
  pre.raw {{
    margin:6px 0 0; padding:6px 8px; background:#0d100a; border:1px solid var(--line);
    border-radius:6px; color:var(--text); font-size:11px; line-height:1.3; overflow-x:auto;
    white-space:pre;
  }}
  label.chk {{ display:flex; gap:7px; align-items:center; margin-top:8px; cursor:pointer;
    font-size:12.5px; color:var(--text); user-select:none; }}
  label.chk input {{ width:16px; height:16px; accent-color:var(--amber); }}
  /* P5 */
  .p5row {{ display:flex; flex-wrap:wrap; gap:8px; align-items:center; margin:8px 0; }}
  #nonce {{
    width:130px; padding:10px 12px; font:inherit; color:var(--text); background:var(--panel);
    border:1px solid var(--line); border-radius:8px;
  }}
  #p5out {{
    font-size:26px; letter-spacing:3px; color:var(--green); margin:8px 0 2px;
    text-shadow:0 0 10px #7ee08133; min-height:32px;
  }}
  .keynote {{ color:var(--red); font-size:12px; margin-top:6px; }}
  #noresults {{ display:none; color:var(--muted); text-align:center; padding:30px 10px; }}
  footer {{
    max-width:900px; margin:0 auto; padding:18px 16px 40px; color:var(--muted);
    font-size:12px; border-top:1px solid var(--line);
  }}
  footer h3 {{ color:var(--amber-dim); font-size:13px; margin:14px 0 6px; letter-spacing:.5px; }}
  footer ol {{ margin:6px 0; padding-left:20px; }}
  footer code {{ color:var(--tagfg); }}
  @media (max-width:480px) {{
    body {{ font-size:15px; }} h1 {{ font-size:18px; }}
    .tag {{ flex-direction:column; }} .tag .imgwrap {{ width:100%; height:120px; flex-basis:auto; }}
  }}
</style>
</head>
<body>
<div class="warnbar" id="warnbar">
  <b>DO NOT PUBLISH BEFORE DEFCON 34 ENDS</b> &mdash; this page reveals all unlock codes + HR patterns.
  This build uses a <b>TEST</b> secret; the real ARG key is injected only at post-con publish.
  <button type="button" onclick="document.getElementById('warnbar').style.display='none'">hide</button>
</div>
<header>
  <h1>CLIP-BOY &middot; POST-CON COMPANION</h1>
  <div class="sub">Print the tags you missed, track your collection, and finish the ARG &mdash; all offline.</div>
  <div class="controls">
    <input id="q" type="search" inputmode="search" autocomplete="off"
           placeholder="Search tags (title, source, ID)&hellip;" aria-label="Search tags">
    <button class="btn" id="hideCollected" type="button">Hide collected</button>
    <button class="btn" id="resetFilters" type="button">Reset filters</button>
  </div>
  <div class="rarity" id="rarityFilter">
    <span class="lbl">Rarity:</span>
    <button class="rchip on" data-tier="" type="button">All</button>
    <button class="rchip" data-tier="Common" type="button">Common</button>
    <button class="rchip" data-tier="Rare" type="button">Rare</button>
    <button class="rchip" data-tier="Legendary" type="button">Legendary</button>
    <button class="rchip" data-tier="0-Day" type="button">0-Day</button>
  </div>
  <nav class="toc">
    <button class="chip" data-jump="tags">Tags</button>
    <button class="chip" data-jump="p5">P5 Unlock</button>
    <button class="chip" data-jump="about">About</button>
  </nav>
</header>
<main>
  <div class="prog" id="prog"></div>

  <section class="card" id="tags">
    <h2>Collectible Tags &amp; HR Patterns</h2>
    <p>Each tag's <b>bump pattern</b> is the 4&times;4 grid shown below, as you see it on the badge's
    manual-entry screen (hold the badge normally). <b>Raise</b> the filled (amber) cells; leave the
    dark ones flat. The 4 corners are <b>fixed structure</b> (outlined) &mdash; 3 raised, 1 flat
    (bottom-left) &mdash; you don't tap those. Check a tag once you've collected it; your progress is
    saved in this browser only.</p>
    <div class="grid" id="taglist"></div>
    <div id="noresults">No tags match that search.</div>
  </section>

  <section class="card" id="p5">
    <h2>P5 &mdash; ARG Finale Unlock (offline)</h2>
    <p>No phone? Enter the <b>nonce</b> the badge shows you on the P5 call screen (a number 0&ndash;9999)
    and this computes the 8-digit unlock code the same way the badge does:
    <code>HMAC-SHA256(secret, "%04u"(nonce))</code> &rarr; first 4 bytes big-endian &rarr;
    <code>% 100000000</code> &rarr; 8 digits.</p>
    <div class="p5row">
      <input id="nonce" type="number" min="0" max="9999" inputmode="numeric"
             placeholder="nonce e.g. 1804" aria-label="Badge nonce">
      <button class="btn" id="p5go" type="button">Compute code</button>
    </div>
    <div id="p5out">&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;&mdash;</div>
    <div class="keynote"><b>TEST KEY ACTIVE</b> &mdash; codes will NOT match a real badge until the real
    ARG secret is injected at publish time (see checklist below).</div>
  </section>

  <section class="card" id="about">
    <h2>About</h2>
    <p>{n} tags from the Clip-Boy catalog (commit <code>{esc(commit)}</code>, {built}). HR patterns are
    computed in your browser from the same SECDED(12,7) anchor encoder the firmware uses
    (<code>scripts/hr_spec/secded.py</code> + <code>pattern_hardness.py</code>). Prefer a script? The
    Python companion is <code>scripts/id_to_code.py</code> (<code>--all</code>, <code>--missing</code>,
    <code>--have</code>). To 3D-print a tag, see <code>libs/HRCode4x4/examples/hm_codegen.py</code>.</p>
  </section>
</main>
<footer>
  <div>Clip-Boy post-con companion. Generated by <code>scripts/gen_postcon_site.py</code>. All logic is
  client-side; collectible images load from <code>clipboy.netlify.app</code>.</div>
  <h3>PUBLISH CHECKLIST (human, at post-con)</h3>
  <ol>
    <li>Confirm DEFCON 34 is <b>over</b> before doing anything below.</li>
    <li>In <code>scripts/gen_postcon_site.py</code>, replace <code>TEST_SECRET_HEX</code> with the real
    <code>ARG_HMAC_SECRET_HEX</code> from 1Password (64-char hex). Re-run the generator. <b>Do not
    commit the file carrying the real secret.</b></li>
    <li>Verify a nonce against a live badge before sharing (compute here, compare to the badge's P5 screen).</li>
    <li>Copy <code>postcon/index.html</code> into the public <code>SafeHazard/Clip-Boy</code> clone, remove
    the DO-NOT-PUBLISH banner + HTML comment, and enable GitHub Pages there.</li>
    <li>Never push the real secret to the private OR public repo &mdash; publish only the rendered HTML.</li>
  </ol>
</footer>
<script>
(function(){{
  "use strict";
  var CATALOG = {data_json};
  // TEST secret only (32 bytes of 0x11).
  // POST-CON PUBLISH: replace TEST_SECRET_HEX with the real ARG_HMAC_SECRET_HEX
  // (from 1Password) at publish time. NEVER commit the real secret.
  var TEST_SECRET_HEX = "{TEST_SECRET_HEX}";
  var IMG_BASE = "{IMG_BASE}";

  // ---- HR anchor encoder, JS port of scripts/hr_spec/secded.py + pattern_hardness.py ----
  var PPOS = [1,2,4,8], DPOS = [3,5,6,7,9,10,11];
  var CELL_ORDER = [[0,1],[0,2],[1,0],[1,1],[1,2],[1,3],[2,0],[2,1],[2,2],[2,3],[3,1],[3,2]];
  function secdedEncode(id7){{
    var h = new Array(12).fill(0);           // h[1..11] used
    for(var i=0;i<7;i++) h[DPOS[i]] = (id7>>i)&1;
    for(var pi=0;pi<PPOS.length;pi++){{
      var p=PPOS[pi], s=0;
      for(var j=1;j<12;j++) if(j!==p && (j&p)) s^=h[j];
      h[p]=s;
    }}
    var overall=0; for(var j=1;j<12;j++) overall^=h[j];
    var out=[]; for(var j=1;j<12;j++) out.push(h[j]); out.push(overall);
    return out;
  }}
  function gridFor(id){{
    var cw = secdedEncode(id);
    var g = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]];
    g[0][0]=1; g[0][3]=1; g[3][0]=1; g[3][3]=0;   // anchors + guard
    for(var k=0;k<CELL_ORDER.length;k++){{ var rc=CELL_ORDER[k]; g[rc[0]][rc[1]]=cw[k]; }}
    return g;
  }}
  function userView(id){{
    var g = gridFor(id), u=[];
    for(var r=0;r<4;r++){{ var row=[]; for(var c=0;c<4;c++) row.push(g[r][3-c]); u.push(row); }}
    return u;   // X-mirrored: badge manual-entry view
  }}
  // In user-view, fixed corners are (0,0),(0,3),(3,3) raised anchors + (3,0) flat guard.
  var FIXED = {{"0,0":1,"0,3":1,"3,0":1,"3,3":1}};
  // Map a tier string to its color-coding CSS class.
  function tierClass(tier){{
    var t = (tier||"").toLowerCase();
    if(t === "common") return "t-common";
    if(t === "rare") return "t-rare";
    if(t === "legendary") return "t-legendary";
    if(t === "0-day") return "t-0day";
    return "";
  }}

  // ---- collection state (localStorage) ----
  var LS_KEY = "clipboy_postcon_collected";
  var collected = {{}};
  try {{ collected = JSON.parse(localStorage.getItem(LS_KEY) || "{{}}") || {{}}; }} catch(e){{ collected = {{}}; }}
  function saveCollected(){{ try {{ localStorage.setItem(LS_KEY, JSON.stringify(collected)); }} catch(e){{}} }}

  var list = document.getElementById("taglist");
  var noresults = document.getElementById("noresults");
  var progEl = document.getElementById("prog");
  var hideBtn = document.getElementById("hideCollected");
  var qEl = document.getElementById("q");
  var hideCollected = false;
  var tierFilter = "";   // "" = All; else exact tier string (Common/Rare/Legendary/0-Day)

  function esc(s){{ return String(s).replace(/[&<>"]/g, function(c){{
    return {{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}}[c]; }}); }}

  function gridHTML(uv){{
    var h="";
    for(var r=0;r<4;r++) for(var c=0;c<4;c++){{
      var cls="c"; if(uv[r][c]) cls+=" on"; if(FIXED[r+","+c]) cls+=" fix";
      h+='<div class="'+cls+'"></div>';
    }}
    return '<div class="g4">'+h+'</div>';
  }}

  function buildCards(){{
    var frag = document.createDocumentFragment();
    CATALOG.forEach(function(t){{
      var uv = userView(t.id);
      var el = document.createElement("div");
      el.className = "tag" + (collected[t.id] ? " done":"");
      el.setAttribute("data-id", t.id);
      el.setAttribute("data-tier", t.tier || "");
      el.setAttribute("data-search", (t.title+" "+t.source+" "+t.id+" "+t.tier).toLowerCase());
      var tier = t.tier ? '<span class="tier '+tierClass(t.tier)+'">'+esc(t.tier)+'</span>' : '';
      el.innerHTML =
        '<div class="imgwrap"><img loading="lazy" alt="'+esc(t.title)+'" '+
          'src="'+IMG_BASE+'/'+t.id+'" '+
          'onerror="this.style.display=\\'none\\';this.parentNode.innerHTML=\\'<div class=ph>no image</div>\\'"></div>'+
        '<div class="meta">'+
          '<div class="title">'+esc(t.title)+tier+'</div>'+
          '<div class="idline">ID '+t.id+(t.source?' &middot; '+esc(t.source):'')+'</div>'+
          '<div class="patt">'+gridHTML(uv)+'</div>'+
          '<label class="chk"><input type="checkbox" '+(collected[t.id]?'checked':'')+'> Collected</label>'+
        '</div>';
      var cb = el.querySelector('input[type=checkbox]');
      cb.addEventListener("change", function(){{
        if(cb.checked) collected[t.id]=1; else delete collected[t.id];
        el.classList.toggle("done", cb.checked);
        saveCollected(); updateProg(); applyFilter();
      }});
      frag.appendChild(el);
    }});
    list.appendChild(frag);
  }}

  function updateProg(){{
    var have = CATALOG.filter(function(t){{ return collected[t.id]; }}).length;
    progEl.innerHTML = "Collected <b>"+have+"</b> of "+CATALOG.length+" tags.";
  }}

  function applyFilter(){{
    // All three filters AND together: search term, rarity, and hide-collected.
    var term = (qEl.value||"").trim().toLowerCase();
    var any=false;
    Array.prototype.forEach.call(list.children, function(el){{
      var id = el.getAttribute("data-id");
      var hitSearch = !term || el.getAttribute("data-search").indexOf(term) !== -1;
      var hitTier = !tierFilter || el.getAttribute("data-tier") === tierFilter;
      var hideThis = hideCollected && collected[id];
      var show = hitSearch && hitTier && !hideThis;
      el.style.display = show ? "" : "none";
      if(show) any=true;
    }});
    noresults.style.display = any ? "none" : "";
  }}

  buildCards(); updateProg(); applyFilter();
  qEl.addEventListener("input", applyFilter);
  hideBtn.addEventListener("click", function(){{
    hideCollected = !hideCollected;
    hideBtn.classList.toggle("on", hideCollected);
    hideBtn.textContent = hideCollected ? "Show collected" : "Hide collected";
    applyFilter();
  }});
  var rchips = document.querySelectorAll("#rarityFilter .rchip");
  Array.prototype.forEach.call(rchips, function(chip){{
    chip.addEventListener("click", function(){{
      tierFilter = chip.getAttribute("data-tier") || "";
      Array.prototype.forEach.call(rchips, function(o){{ o.classList.toggle("on", o === chip); }});
      applyFilter();
    }});
  }});
  document.getElementById("resetFilters").addEventListener("click", function(){{
    qEl.value=""; hideCollected=false; hideBtn.classList.remove("on");
    hideBtn.textContent="Hide collected";
    tierFilter="";
    Array.prototype.forEach.call(rchips, function(o){{ o.classList.toggle("on", !o.getAttribute("data-tier")); }});
    applyFilter();
  }});
  Array.prototype.forEach.call(document.querySelectorAll(".chip"), function(b){{
    b.addEventListener("click", function(){{
      var el = document.getElementById(b.getAttribute("data-jump"));
      if(el) el.scrollIntoView({{behavior:"smooth", block:"start"}});
    }});
  }});

  // ---- P5 unlock computer (WebCrypto), mirrors arg_unlock.h ----
  function hexToBytes(hex){{
    var a = new Uint8Array(hex.length/2);
    for(var i=0;i<a.length;i++) a[i] = parseInt(hex.substr(i*2,2),16);
    return a;
  }}
  var p5out = document.getElementById("p5out");
  async function p5code(nonce){{
    var nb = ("0000" + (nonce % 10000)).slice(-4);   // "%04u"
    var key = await crypto.subtle.importKey("raw", hexToBytes(TEST_SECRET_HEX),
      {{name:"HMAC", hash:"SHA-256"}}, false, ["sign"]);
    var sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(nb));
    var b = new Uint8Array(sig);
    var u = (((b[0]<<24)>>>0) + (b[1]<<16) + (b[2]<<8) + b[3]) >>> 0;  // BE uint32
    var code = u % 100000000;                                          // mod 1e8
    return ("00000000" + code).slice(-8);                             // "%08u"
  }}
  function runP5(){{
    var v = document.getElementById("nonce").value;
    if(v === "" || isNaN(parseInt(v,10))){{ p5out.textContent="\\u2014".repeat(8); return; }}
    var nonce = ((parseInt(v,10) % 10000) + 10000) % 10000;
    p5out.textContent = "\\u2026";
    p5code(nonce).then(function(code){{ p5out.textContent = code; }})
      .catch(function(e){{ p5out.textContent = "error: " + e; }});
  }}
  document.getElementById("p5go").addEventListener("click", runP5);
  document.getElementById("nonce").addEventListener("keydown", function(e){{
    if(e.key === "Enter") runP5();
  }});
}})();
</script>
</body>
</html>
"""


def main():
    out = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUT
    catalog = load_catalog()
    doc = render(catalog)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(doc)
    print(f"gen_postcon_site: {len(catalog)} tags -> {out}")


if __name__ == "__main__":
    main()
