#!/usr/bin/env python3
r"""
SpaceBadge Drone Scan -- Windows BLE test transmitter
=====================================================
Broadcasts a SIMULATED drone's Remote ID over Bluetooth LE so you can test
the badge's Drone Scan screen without a real drone in the air.

It advertises ASTM F3411 / Open Drone ID service data (16-bit UUID 0xFFFA),
cycling through Basic ID / Location / System / Operator ID / Self ID messages
-- the exact byte payloads were generated and round-trip-verified with the
opendroneid reference library, so the badge should decode them cleanly and
show ONE drone ("SPACEBADGE-SIM-0001") that fills in over a few seconds.

RECEIVE-ONLY on the badge side; this side only transmits a made-up test drone.

Requires: Windows 10/11 with Bluetooth, Python 3.9+, and:
    pip install winsdk
Run (from this folder):
    python rid_sim_windows.py
Stop with Ctrl+C.

If Windows refuses to advertise service data (some adapters/driver stacks
only allow manufacturer data), the script says so -- see the fallback notes
printed on failure.
"""
import asyncio
import sys

# 25-byte Open Drone ID messages (hex), generated by encode.c and verified by
# decoding them back through decodeOpenDroneID(). Do not edit by hand.
MESSAGES = {
    "Basic ID":    "0212535041434542414447452d53494d2d3030303100000000",
    "Location":    "12205a2001b8168f15900f5fbba80cd00cc0084a32b0040500",
    "System":      "420070228f15d8035fbb0100000000000000940c0000000000",
    "Operator ID": "520046412d53494d2d544553542d3030303100000000000000",
    "Self ID":     "32005370616365426164676520546573742054617267657400",
}
ORDER = ["Basic ID", "Location", "System", "Operator ID", "Self ID"]

SERVICE_UUID_LE = bytes([0xFA, 0xFF])  # 0xFFFA, little-endian
ODID_APP_CODE = 0x0D                    # ASTM F3411 BT app code
ADV_INTERVAL_S = 3.0                    # per-message dwell (give it time to get on air)

try:
    from winsdk.windows.devices.bluetooth.advertisement import (
        BluetoothLEAdvertisement,
        BluetoothLEAdvertisementDataSection,
        BluetoothLEAdvertisementPublisher,
        BluetoothLEAdvertisementPublisherStatus,
    )
    from winsdk.windows.storage.streams import DataWriter
except ImportError:
    print("ERROR: winsdk not installed. Run:  pip install winsdk")
    sys.exit(1)


def build_section(msg_hex: str, counter: int) -> BluetoothLEAdvertisementDataSection:
    """Service Data - 16-bit UUID (AD type 0x16):
       [UUID_lo UUID_hi][app_code][msg_counter][25-byte ODID message]"""
    msg = bytes.fromhex(msg_hex)
    assert len(msg) == 25, "ODID message must be 25 bytes"
    payload = SERVICE_UUID_LE + bytes([ODID_APP_CODE, counter & 0xFF]) + msg
    writer = DataWriter()
    writer.write_bytes(payload)
    section = BluetoothLEAdvertisementDataSection()
    section.data_type = 0x16  # Service Data - 16-bit UUID
    section.data = writer.detach_buffer()
    return section


async def main():
    print("SpaceBadge RID simulator -- broadcasting test drone 'SPACEBADGE-SIM-0001'")
    print("Open the badge's Drone Scan screen. Ctrl+C here to stop.\n")
    counter = 0
    publisher = None
    try:
        while True:
            for name in ORDER:
                # Rebuild a fresh publisher per message so Windows re-emits the
                # changed advertisement payload immediately.
                if publisher is not None and \
                   publisher.status == BluetoothLEAdvertisementPublisherStatus.STARTED:
                    publisher.stop()

                adv = BluetoothLEAdvertisement()
                adv.data_sections.append(build_section(MESSAGES[name], counter))
                publisher = BluetoothLEAdvertisementPublisher(adv)
                try:
                    publisher.start()
                except Exception as e:  # noqa
                    print(f"Windows refused the advertisement: {e}")
                    print_fallback()
                    return

                # Wait for the advertiser to actually reach STARTED (async on Windows)
                status = publisher.status
                for _ in range(20):  # up to ~2s
                    status = publisher.status
                    if status in (BluetoothLEAdvertisementPublisherStatus.STARTED,
                                  BluetoothLEAdvertisementPublisherStatus.ABORTED):
                        break
                    await asyncio.sleep(0.1)

                if status == BluetoothLEAdvertisementPublisherStatus.ABORTED:
                    print("Advertisement ABORTED by Windows (service data not permitted "
                          "on this adapter).")
                    print_fallback()
                    return

                print(f"  broadcasting: {name:12s} (counter {counter})  "
                      f"status={status.name}")
                counter = (counter + 1) & 0xFF
                await asyncio.sleep(ADV_INTERVAL_S)
    except KeyboardInterrupt:
        pass
    finally:
        try:
            if publisher is not None:
                publisher.stop()
        except Exception:
            pass
        print("\nStopped. Test drone should age out of the badge in ~90s.")


def print_fallback():
    print("\n--- Fallback options ---")
    print("1. Confirm your PC's Bluetooth is ON and the adapter supports LE.")
    print("2. Some Windows BT driver stacks only allow *manufacturer* data, not")
    print("   service data. If so, BLE-from-Windows won't work for RID and the")
    print("   most reliable simulator is a spare ESP32 flashed as a transmitter")
    print("   (ask Claude to build that firmware -- it takes a couple minutes).")


if __name__ == "__main__":
    asyncio.run(main())
